module comp4bit();
reg [3:0] a,b;
wire g,l,e;
comp4bit UUT (a,b,g,l,e);
initial begin
a=15; b=11; #100
a=12; b=10; #100
a=2; b=2; #100
a=9; b=10; #100
a=14; b=0; #100;
end
endmodule
